%define MULTIBOOT2_HEADER_MAGIC 0xe85250d6
%define MULTIBOOT_ARCHITECTURE_I386 0

section .multiboot-header
dd MULTIBOOT2_HEADER_MAGIC
dd MULTIBOOT_ARCHITECTURE_I386
dd 0
dd -(MULTIBOOT2_HEADER_MAGIC+MULTIBOOT_ARCHITECTURE_I386)
